project:
  type: website
  output-dir: docs
  resources:
    - ".nojekyll"

website:
  title: "CIRCE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: Members
      - href: meetings/index.qmd
        text: Events
      - href: links.qmd
        text: Resources
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc_depth: 2
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true


