project:
  type: website
  output-dir: docs
  resources:
    - ".nojekyll"

website:
  title: "CIRCE"
  search: false
  navbar:
    logo: "images/circe_logo_final.jpg"
    title: false
    background: white
    foreground: dark
    left:
      - href: about.qmd
        text: About
      - href: people.qmd
        text: Members
      - href: meetings/index.qmd
        text: Events
      - href: links.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
      

format:
  html:
    theme: lux
    css: styles.css
    toc: false


